name: simple-rag-chat

services:
  app:
    image: simple-rag-chat:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ${PWD}/config.yaml:/app/config/config.yaml
