name: simple-rag-chat

services:
  llama-cpp-server:
    image: local/llama.cpp:server-cuda
    volumes:
      - ${PWD}/models:/models
    command: 
      - "-m"
      - "/models/Meta-Llama-3.1-8B-Instruct-Q6_K_L.gguf"
      - "--port"
      - "8000"
      - "--host"
      - "0.0.0.0"
      - "-n"
      - "512"
      - "--n-gpu-layers"
      - "3"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  app:
    depends_on:
      llama-cpp-server:
        condition: service_healthy
